<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis" Version="1.34.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.34.0" />
    <PackageReference Include="Google.Apis.Calendar.v3" Version="1.34.0.1244" />
    <PackageReference Include="Google.Apis.Core" Version="1.34.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="client_secret.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
